# ----- Github Action -----
# 必要な時に手で実行
name: workflow_dispatch

on: workflow_dispatch

jobs:
  FEC-dispatch:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Checkout Branch
        uses: actions/checkout@main
      # Install
      - name: Install Projest
        run: npm install
      # Fix
      - name: Run Fix
        run: npm run fix:all
      # Test
      - name: Run Test
        run: npm run test:coverage
      # Check
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
