# ----- Github Action -----
# branch mergeの時、コード、コードフォーマット、JSONファイルをチェック
name: merge

on:
  pull_request:
    types:
      - closed

jobs:
  FEC-merge:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Checkout Branch
        uses: actions/checkout@main
      # Install
      - name: Install Projest
        run: npm install
      # Fix
      - name: Run Fix
        run: npm run fix:all
      # Check
      - name: Run Check
        run: npm run check:all
