# ----- Github Action -----
name: pull_request

# on: workflow_dispatch
on: [pull_request]

jobs:
  FEC-pull_request:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Checkout Branch
        uses: actions/checkout@main
      # Install
      - name: Install Projest
        run: npm install
      # Fix
      - name: Run Fix
        run: npm run fix:all
      # Check
      - name: Run Check
        run: npm run check:all
