# ----- Github Action -----
name: FEC-pull_request
# 実行のタイミング
# on: workflow_dispatch
on: [pull_request]
# 実行の流れ
jobs:
  FEC-Pull-Request:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Checkout Branch
        uses: actions/checkout@main
      # Install
      - name: Install Projest
        run: npm install
      # Fix Format
      - name: Run Fix Format
        run: npm run format:fix
      # Check
      - name: Run Check
        run: npm run check:all
