# ----- Github Action -----
name: workflow_dispatch
# 実行のタイミング
on: workflow_dispatch
# 実行の流れ
jobs:
  FEC-dispatch:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Checkout Branch
        uses: actions/checkout@main
      # Install
      - name: Install Projest
        run: npm install
      # Fix
      - name: Run Fix
        run: npm run fix:all
      # Check
      - name: Run Check
        run: npm run check:all
